services:
  web:
    image: order
    container_name: order-management-api
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=mongodb://db:27017/order_management
    depends_on:
      - db

  db:
    image: order
    container_name: order-management-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: my-secret-pw
      MONGO_INITDB_DATABASE: order_management
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/db

  test-db:
    image: order
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test-secret-pw
    volumes:
      - test_db_data:/data/db

volumes:
  db_data:
  test_db_data:
